# Generated by Django 3.0.3 on 2020-07-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abmublog', '0006_makeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='type',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='abmublog.Product'),
        ),
    ]
