# Generated by Django 3.0.3 on 2020-07-15 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abmublog', '0007_auto_20200713_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeorder',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
