# Generated by Django 3.0.3 on 2020-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abmublog', '0008_makeorder_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='makeorder',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
