# Generated by Django 3.0.3 on 2020-07-18 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abmublog', '0009_auto_20200715_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
