# Generated by Django 3.0.3 on 2020-07-22 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abmublog', '0010_auto_20200718_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeorder',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
